✨ TJ-64 GNB 기능 (현재 작업중)
the-julge/the-julge pull request #35
Opened 2024-03-19 14:51 UTC by whtjdrud

## 주요 변경 사항

- 로그인 권한 별로 보여지는 화면 다르게 하기
- 로그아웃 처리(너무 어거지로 한거 같은데) 일단 완성

## 앞으로 해야할것
- 실제 데이터 연동 테스트 (일단 데이터 연동 기능은 만들어둠) 
- (만약 알림이 있을경우 주황색으로 보이게 해둠) 실제 데이터가 있어야..
- 알림 읽음 처리 개발해야함
-
## 관련 이슈

-
-

## 관련 스크린샷
비로그인
![image](이미지url)
업주님
![image](https://github.com/the-julge/the-julge/assets/151587265/a70b189a-59f9-4666-92bc-27f3cf0df3b3)
알바님
![image](https://github.com/the-julge/the-julge/assets/151587265/542f7e91-e556-4483-97df-f160a2f6c01e)
로그아웃
![로그아웃](https://github.com/the-julge/the-julge/assets/151587265/30d6b57b-1d63-44ed-8c98-da48e056b12b)

## 테스트 계획 또는 완료 사항

-
-

## 리뷰어에게

- 이거 예전에 만들었던 브랜치로 `git merge develop` 했더니 커밋이 160 정도 쌓여있어서 문제 없는건가 테스트용입니다.
- 
-

2024-03-19 15:07 UTC, midcondria requested changes
고생하셨습니다.
로그아웃 부분 한번만 봐주세요!

2024-03-19 15:07 UTC, midcondria commented on components/Gnb/components/HeaderButtons.tsx
> +      {userType === "" && (
```
userType && <컴포넌트> 
```
이렇게 해도 되지 않을까 하는 생각이 들어요!

2024-03-19 15:07 UTC, midcondria commented on components/Gnb/components/UiGnb.tsx
> +  userType = "guest",
혹시 userType의 기본값이 guest인 이유가 있나요?

2024-03-19 15:07 UTC, midcondria commented on components/Gnb/hook/useLogout.ts
> +  document.cookie = "userType=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;";
저도 이렇게 로그아웃 구현할거 같아요.
이쪽에서는 `accessToken=;` 이 아니라 `jwt=;` 으로 해야하지 않을까 싶습니다!

2024-03-19 15:38 UTC, whtjdrud commented on components/Gnb/components/UiGnb.tsx
> +  userType = "guest",
처음에 Gnb만들때 명시적으로 비로그인 상태를 나타내려고 guest로 했는데
이번에 작업해주셔서 ""를 기본값으로 하셔서 의미없는 데이터가 되었네요. 삭제 하도록 하겠습니다.

2024-03-19 15:40 UTC, whtjdrud commented on components/Gnb/components/HeaderButtons.tsx
> +      {userType === "" && (
빈값이 falsy인가 그래서 출력이 안되지 않나용?

2024-03-19 15:45 UTC, midcondria commented on components/Gnb/components/HeaderButtons.tsx
> +      {userType === "" && (
아 `||`랑 헷갈렸네요.
userType이 없으면 로그인 버튼, 있으면 로그인 상태 UI인줄 알았어요.
회원이나 사장님 UI가 똑같은줄 알았는데 두개 다른가봐요. 
그대로 가셔도 좋을것 같습니다!

2024-03-19 15:47 UTC, midcondria submitted a review, later dismissed

2024-03-19 15:47 UTC, midcondria commented on components/Gnb/hook/useLogout.ts
> +      "userType=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;";
저도 이렇게 로그아웃 구현했을거 같아요. :thumbsup: 
이쪽에서는 `accessToken=;` 이 아니라 `jwt=;` 으로 해야하지 않을까 싶습니다!

2024-03-20 02:55 UTC, soyxxn approved these changes
![SnkGIF](https://github.com/the-julge/the-julge/assets/151617960/ee4ac1f6-2448-4d91-8ca8-f6a98b48d071)

2024-03-20 06:37 UTC, yuyoni reviewed
작업중이라고 하셔서 일단 승인 및 머지는 미루겠습니다..!

2024-03-21 13:37 UTC, whtjdrud commented on components/Gnb/hook/useLogout.ts
> +      "userType=; Path=/; Expires=Thu, 01 Jan 1970 00:00:01 GMT;";
수정해두고 댓글을 안달았네요. 죄송합니다.

commit : [53b4307](https://github.com/the-julge/the-julge/pull/35/commits/53b430752b287192213f8a9a7c9cfc64f8fdf91d)

2024-03-21 14:05 UTC, yuyoni approved these changes
수고하셨습니다~~

2024-03-21 14:09 UTC, merged